[package]
name = "toniefile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.6"
# audiopus = { git = "https://github.com/Lakelezz/audiopus" }
audiopus = "^0.2"
libogg = { git = "https://github.com/Schievel1/libogg-rs" }
prost = "0.6"
# Only necessary if using Protobuf well-known types:
prost-types = "0.6"
byteorder = "1.5.0"
anyhow = "*" # TODO get rid if this later


[build-dependencies]
prost-build = { version = "0.6" }
